---

# Configure DHCP server
- name: Update dhcpd 
  blockinfile:
    path: /etc/dhcpcd.conf
    backup: yes
    block: |
      interface eth0
      static ip_address=10.0.0.1/24
      static domain_name_servers=8.8.8.8,8.8.4.4
      nolink


# Install dnsmasq
- name: Install dnsmasq
  apt:
    name=dnsmasq
    state=present
    update_cache=yes


# Configure dnsmasq
- name: Configure dnsmasq
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes


# Bugfix dnsmasq
- name: Bugfix dnsmasq
  blockinfile:
    path: /etc/init.d/dnsmasq
    insertafter: "#!/bin/sh"
    block: |
      # Hack to wait until dhcpcd is ready
      sleep 10 


# Add forwarding
- name: Add forwarding
  replace:
    path: /etc/sysctl.conf
    backup: yes
    regexp: '^#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'


# Update iptables
- name: Iptable rule 1
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: wlan0
    jump: MASQUERADE


# Update iptables
- name: Iptable rule 2
  iptables:
    table: filter
    chain: FORWARD
    in_interface: wlan0
    out_interface: eth0
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    
 
# Update iptables
- name: Iptable rule 3
  iptables:
    table: filter
    chain: FORWARD
    in_interface: eth0
    out_interface: wlan0
    jump: ACCEPT

# Update iptables
# Allow api calls to master node on port 6443
# iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 6443 -j DNAT --to-destination 10.0.0.50:6443


# Iptables persistant
- name: Prevent the iptables-peristent install dialog
  debconf: name=iptables-persistent question={{ item }} vtype=boolean value=true
  with_items:
  - iptables-persistent/autosave_v4
  - iptables-persistent/autosave_v6


# Install iptables-persistent
- name: install iptables-persistent
  apt: name=iptables-persistent
